In [1]:
import pandas as pd

df = pd.read_excel('Kenya_Financial_Data_CLEAN.xlsx')
df = df.iloc[:15,:16]


print(df.shape)
print(df.head())
print(df.info())

(15, 16)
                                      Indicator Name         2010  \
0  Unemployment, total (% of total labor force) (...        2.793
1  Foreign direct investment, net inflows (% of GDP)     0.392164
2                              GDP growth (annual %)     8.058474
3                       GDP per capita (current US$)  1091.518731
4  Borrowers from commercial banks (per 1,000 adu...    76.486104

          2011         2012         2013         2014         2015  \
0        2.699        2.678        2.762        2.767        2.762
1     3.094711     2.447259      1.81417     1.202208       0.8838
2     5.121106      4.56868     3.797848     5.020111     4.967721
3  1096.144998  1285.005362  1370.878852  1482.815663  1489.119598
4    82.286268     82.25932   119.044228   164.093378   226.327909

          2016         2017         2018         2019         2020  \
0     2.757000     3.542000     4.284000     5.014000     5.613000
1     0.627591     1.640837     0.832686     0.468169    -0.005368
2     4.213517     3.837958     5.647946     5.114159    -0.272766
3  1554.126103  1667.484472  1836.452755  1960.408089  1927.664590
4   277.505896   245.078616   240.191141   271.115581   360.204778

          2021         2022         2023         2024
0     5.693000     5.565000     5.409000     5.487000
1     0.382594     0.691646     0.472521     0.384925
2     7.590489     4.859981     5.719992     4.660196
3  2061.356221  2109.562885  1942.588028  2133.461934
4   398.921846   429.857310   373.191306   324.896861
<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Indicator Name  15 non-null     str
 1   2010            14 non-null     object
 2   2011            15 non-null     object
 3   2012            14 non-null     object
 4   2013            14 non-null     object
 5   2014            15 non-null     object
 6   2015            14 non-null     object
 7   2016            14 non-null     float64
 8   2017            15 non-null     float64
 9   2018            14 non-null     float64
 10  2019            14 non-null     float64
 11  2020            14 non-null     float64
 12  2021            15 non-null     float64
 13  2022            14 non-null     float64
 14  2023            14 non-null     float64
 15  2024            14 non-null     float64
dtypes: float64(9), object(6), str(1)
memory usage: 2.0+ KB
None

In [2]:
indicators_to_keep = [
    'GDP growth (annual %)',
    'Bank nonperforming loans to total gross loans (%)',
    'Inflation, consumer prices (annual %)',
    'Lending interest rate (%)',
    'Deposit interest rate (%)',
    'Interest rate spread (lending rate minus deposit rate, %)'
]

df_clean = df[df['Indicator Name'].isin(indicators_to_keep)]
print(df_clean)

                                       Indicator Name      2010       2011  \
2                               GDP growth (annual %)  8.058474   5.121106
5   Bank nonperforming loans to total gross loans (%)  5.132644   4.421192
6   Interest rate spread (lending rate minus depos...  9.814133   9.418197
7               Inflation, consumer prices (annual %)  3.961389  14.022491
11                          Deposit interest rate (%)  4.557367   5.628563
13                          Lending interest rate (%)   14.3715   15.04676

         2012       2013       2014       2015       2016       2017  \
2     4.56868   3.797848   5.020111   4.967721   4.213517   3.837958
5     4.59096   5.043583    5.45512   5.988764   8.585968   9.949128
6    8.151262   8.671688   8.140551   6.897669   7.871005   5.993449
7     9.37777   5.717494   6.878155   6.582154   6.297250   8.005650
11  11.572145    8.64177    8.37338   9.188945   8.688626   7.674123
13  19.723407  17.313458  16.513931  16.086614  16.559631  13.667573

         2018       2019       2020       2021       2022       2023  \
2    5.647946   5.114159  -0.272766   7.590489   4.859981   5.719992
5   12.026729   9.749355  11.878576  10.886463  10.753110  12.335551
6    4.768059   4.935063   5.027081   5.393025   5.190665   4.420812
7    4.689806   5.239638   5.405162   6.107936   7.659863   7.671396
11   8.292700   7.506070   6.968703   6.686974   7.145176   9.167690
13  13.060759  12.441133  11.995785  12.079998  12.335841  13.588502

         2024
2    4.660196
5   13.572976
6    4.610797
7    4.489789
11  11.982310
13  16.593107

In [3]:
gdp_row = df_clean[df_clean['Indicator Name']=='GDP growth (annual %)']
gdp_values = gdp_row.iloc[0,1:].astype(float)

print(f"min:{gdp_values.min()}")
print(f"max:{gdp_values.max()}")
print(f"average:{gdp_values.mean()}")

min:-0.2727663274388163
max:8.05847360290906
average:4.860360860850938

In [4]:
print(df_clean['Indicator Name'].unique())

<StringArray>
[                                    'GDP growth (annual %)',
         'Bank nonperforming loans to total gross loans (%)',
 'Interest rate spread (lending rate minus deposit rate, %)',
                     'Inflation, consumer prices (annual %)',
                                 'Deposit interest rate (%)',
                                 'Lending interest rate (%)']
Length: 6, dtype: str

In [5]:
npl_ratio = df_clean[df_clean['Indicator Name']=='Bank nonperforming loans to total gross loans (%)']
npl_values = npl_ratio.iloc[0,1:].astype(float)
inflation_rate = df_clean[df_clean['Indicator Name']== 'Inflation, consumer prices (annual %)']
inflation_values = inflation_rate.iloc[0,1:].astype(float)
print(f"min:{npl_values.min()}")
print(f"max:{npl_values.max()}")
print(f"average:{npl_values.mean()}")
print(f"min:{inflation_values.min()}")
print(f"max:{inflation_values.max()}")
print(f"average:{inflation_values.mean()}")

min:4.42119245549814
max:13.5729761304392
average:8.691341349295923
min:3.961388891153851
max:14.02249130147042
average:6.807062827074548

In [6]:
indicators = df_clean['Indicator Name'].unique()
for Indicator_name in indicators:
    indicator_row = df_clean[df_clean['Indicator Name']== Indicator_name]
    values = indicator_row.iloc[0,1:].astype(float)
    min_val= values.min()
    max_val= values.max()
    avg_val= values.mean()
    print(f"{Indicator_name}:min={min_val:.2f},max={max_val:.2f},average={avg_val:.2f}")

GDP growth (annual %):min=-0.27,max=8.06,average=4.86
Bank nonperforming loans to total gross loans (%):min=4.42,max=13.57,average=8.69
Interest rate spread (lending rate minus deposit rate, %):min=4.42,max=9.81,average=6.62
Inflation, consumer prices (annual %):min=3.96,max=14.02,average=6.81
Deposit interest rate (%):min=4.56,max=11.98,average=8.14
Lending interest rate (%):min=12.00,max=19.72,average=14.76

In [7]:
gdp_row = df_clean[df_clean['Indicator Name']== 'GDP growth (annual %)']
gdp_values = gdp_row.iloc[0,1:].astype(float)

gdp_change = gdp_values.diff()
print("gdp_values:")
print(gdp_values)
print("\n year-on-year change:")
print(gdp_change)

gdp_values:
2010    8.058474
2011    5.121106
2012    4.568680
2013    3.797848
2014    5.020111
2015    4.967721
2016    4.213517
2017    3.837958
2018    5.647946
2019    5.114159
2020   -0.272766
2021    7.590489
2022    4.859981
2023    5.719992
2024    4.660196
Name: 2, dtype: float64

 year-on-year change:
2010         NaN
2011   -2.937367
2012   -0.552427
2013   -0.770831
2014    1.222263
2015   -0.052390
2016   -0.754204
2017   -0.375559
2018    1.809988
2019   -0.533788
2020   -5.386925
2021    7.863256
2022   -2.730508
2023    0.860011
2024   -1.059796
Name: 2, dtype: float64

In [8]:
npl_ratio = df_clean[df_clean['Indicator Name']=='Bank nonperforming loans to total gross loans (%)']
npl_values = npl_ratio.iloc[0,1:].astype(float)
npl_change = npl_values.diff()
print("npl_values:")
print(npl_values)
print("\n year on year change:")
print(npl_change)

npl_values:
2010     5.132644
2011     4.421192
2012     4.590960
2013     5.043583
2014     5.455120
2015     5.988764
2016     8.585968
2017     9.949128
2018    12.026729
2019     9.749355
2020    11.878576
2021    10.886463
2022    10.753110
2023    12.335551
2024    13.572976
Name: 5, dtype: float64

 year on year change:
2010         NaN
2011   -0.711452
2012    0.169768
2013    0.452623
2014    0.411537
2015    0.533644
2016    2.597204
2017    1.363160
2018    2.077601
2019   -2.277374
2020    2.129221
2021   -0.992113
2022   -0.133352
2023    1.582441
2024    1.237425
Name: 5, dtype: float64

In [9]:
indicators = df_clean['Indicator Name'].unique()
for Indicator_name in indicators:
    indicator_row= df_clean[df_clean['Indicator Name']==Indicator_name]
    values = indicator_row.iloc[0,1:].astype(float)
    indicators_change = values.diff()
    print("values:")
    print(values)
    print("\n year on year change:")
    print(indicators_change)

values:
2010    8.058474
2011    5.121106
2012    4.568680
2013    3.797848
2014    5.020111
2015    4.967721
2016    4.213517
2017    3.837958
2018    5.647946
2019    5.114159
2020   -0.272766
2021    7.590489
2022    4.859981
2023    5.719992
2024    4.660196
Name: 2, dtype: float64

 year on year change:
2010         NaN
2011   -2.937367
2012   -0.552427
2013   -0.770831
2014    1.222263
2015   -0.052390
2016   -0.754204
2017   -0.375559
2018    1.809988
2019   -0.533788
2020   -5.386925
2021    7.863256
2022   -2.730508
2023    0.860011
2024   -1.059796
Name: 2, dtype: float64
values:
2010     5.132644
2011     4.421192
2012     4.590960
2013     5.043583
2014     5.455120
2015     5.988764
2016     8.585968
2017     9.949128
2018    12.026729
2019     9.749355
2020    11.878576
2021    10.886463
2022    10.753110
2023    12.335551
2024    13.572976
Name: 5, dtype: float64

 year on year change:
2010         NaN
2011   -0.711452
2012    0.169768
2013    0.452623
2014    0.411537
2015    0.533644
2016    2.597204
2017    1.363160
2018    2.077601
2019   -2.277374
2020    2.129221
2021   -0.992113
2022   -0.133352
2023    1.582441
2024    1.237425
Name: 5, dtype: float64
values:
2010    9.814133
2011    9.418197
2012    8.151262
2013    8.671688
2014    8.140551
2015    6.897669
2016    7.871005
2017    5.993449
2018    4.768059
2019    4.935063
2020    5.027081
2021    5.393025
2022    5.190665
2023    4.420812
2024    4.610797
Name: 6, dtype: float64

 year on year change:
2010         NaN
2011   -0.395937
2012   -1.266935
2013    0.520426
2014   -0.531137
2015   -1.242883
2016    0.973336
2017   -1.877556
2018   -1.225391
2019    0.167004
2020    0.092019
2021    0.365943
2022   -0.202359
2023   -0.769854
2024    0.189985
Name: 6, dtype: float64
values:
2010     3.961389
2011    14.022491
2012     9.377770
2013     5.717494
2014     6.878155
2015     6.582154
2016     6.297250
2017     8.005650
2018     4.689806
2019     5.239638
2020     5.405162
2021     6.107936
2022     7.659863
2023     7.671396
2024     4.489789
Name: 7, dtype: float64

 year on year change:
2010          NaN
2011    10.061102
2012    -4.644721
2013    -3.660276
2014     1.160661
2015    -0.296001
2016    -0.284905
2017     1.708400
2018    -3.315843
2019     0.549831
2020     0.165524
2021     0.702774
2022     1.551927
2023     0.011534
2024    -3.181608
Name: 7, dtype: float64
values:
2010     4.557367
2011     5.628563
2012    11.572145
2013     8.641770
2014     8.373380
2015     9.188945
2016     8.688626
2017     7.674123
2018     8.292700
2019     7.506070
2020     6.968703
2021     6.686974
2022     7.145176
2023     9.167690
2024    11.982310
Name: 11, dtype: float64

 year on year change:
2010         NaN
2011    1.071197
2012    5.943581
2013   -2.930375
2014   -0.268390
2015    0.815566
2016   -0.500320
2017   -1.014502
2018    0.618577
2019   -0.786630
2020   -0.537367
2021   -0.281730
2022    0.458202
2023    2.022515
2024    2.814620
Name: 11, dtype: float64
values:
2010    14.371500
2011    15.046760
2012    19.723407
2013    17.313458
2014    16.513931
2015    16.086614
2016    16.559631
2017    13.667573
2018    13.060759
2019    12.441133
2020    11.995785
2021    12.079998
2022    12.335841
2023    13.588502
2024    16.593107
Name: 13, dtype: float64

 year on year change:
2010         NaN
2011    0.675260
2012    4.676647
2013   -2.409949
2014   -0.799527
2015   -0.427317
2016    0.473017
2017   -2.892058
2018   -0.606814
2019   -0.619626
2020   -0.445348
2021    0.084214
2022    0.255843
2023    1.252661
2024    3.004606
Name: 13, dtype: float64

In [10]:
def classify_npl(npl_ratio):
    if npl_ratio < 5 :
        return "healthy"
    elif npl_ratio <= 10 :
        return "watch"
    else:
        return "critical"
npl_row = df_clean[df_clean['Indicator Name']== 'Bank nonperforming loans to total gross loans (%)']
npl_values = npl_row.iloc[0,1:].astype(float)
npl_classification = npl_values.apply(classify_npl)
print(npl_classification)

2010       watch
2011     healthy
2012     healthy
2013       watch
2014       watch
2015       watch
2016       watch
2017       watch
2018    critical
2019       watch
2020    critical
2021    critical
2022    critical
2023    critical
2024    critical
Name: 5, dtype: str

In [11]:
def classify_gdp(gdp_values):
    if gdp_values > 5 :
        return "strong"
    elif 3<= gdp_values <=5 :
        return "moderate"
    else:
        return "weak"
gdp_row = df_clean[df_clean['Indicator Name']== 'GDP growth (annual %)']
gdp_values = gdp_row.iloc[0,1:].astype(float)
gdp_classification = gdp_values.apply(classify_gdp)
print(gdp_classification)

2010      strong
2011      strong
2012    moderate
2013    moderate
2014      strong
2015    moderate
2016    moderate
2017    moderate
2018      strong
2019      strong
2020        weak
2021      strong
2022    moderate
2023      strong
2024    moderate
Name: 2, dtype: str

In [12]:
indicators = df_clean['Indicator Name'].unique()
print(indicators)

<StringArray>
[                                    'GDP growth (annual %)',
         'Bank nonperforming loans to total gross loans (%)',
 'Interest rate spread (lending rate minus deposit rate, %)',
                     'Inflation, consumer prices (annual %)',
                                 'Deposit interest rate (%)',
                                 'Lending interest rate (%)']
Length: 6, dtype: str

In [13]:
def classify_inflation(inflation_rate):
    if inflation_rate < 5:
        return "low"
    elif 5<= inflation_rate <=10 :
        return "moderate"
    else :
        return "high"
inflation_row = df_clean[df_clean['Indicator Name']=='Inflation, consumer prices (annual %)']
inflation_values = inflation_row.iloc[0,1:].astype(float)
inflation_classification = inflation_values.apply(classify_inflation)
print(inflation_classification)

2010         low
2011        high
2012    moderate
2013    moderate
2014    moderate
2015    moderate
2016    moderate
2017    moderate
2018         low
2019    moderate
2020    moderate
2021    moderate
2022    moderate
2023    moderate
2024         low
Name: 7, dtype: str

In [14]:
summary_data = []
years = [int(col) for col in df_clean.columns[1:]]
for i, year in enumerate (years) :
    row = {'year':year}
    gdp_row = df_clean[df_clean['Indicator Name']=='GDP growth (annual %)']
    gdp_values = float(gdp_row.iloc[0,i+1])
    row['gdp'] = gdp_values
    row['gdp_class']=classify_gdp(gdp_values)
    npl_row = df_clean[df_clean['Indicator Name']=='Bank nonperforming loans to total gross loans (%)']
    npl_values = float(npl_row.iloc[0,i+1])
    row['npl'] = npl_values
    row['npl_class'] = classify_npl(npl_values)
    inflation_row = df_clean[df_clean['Indicator Name']== 'Inflation, consumer prices (annual %)']
    inflation_values = float(inflation_row.iloc[0,i+1])
    row['inflation'] = inflation_values
    row['inflation_class'] = classify_inflation(inflation_values)

    summary_data.append(row)
summary_df = pd.DataFrame(summary_data)
print(summary_df)

    year       gdp gdp_class        npl npl_class  inflation inflation_class
0   2010  8.058474    strong   5.132644     watch   3.961389             low
1   2011  5.121106    strong   4.421192   healthy  14.022491            high
2   2012  4.568680  moderate   4.590960   healthy   9.377770        moderate
3   2013  3.797848  moderate   5.043583     watch   5.717494        moderate
4   2014  5.020111    strong   5.455120     watch   6.878155        moderate
5   2015  4.967721  moderate   5.988764     watch   6.582154        moderate
6   2016  4.213517  moderate   8.585968     watch   6.297250        moderate
7   2017  3.837958  moderate   9.949128     watch   8.005650        moderate
8   2018  5.647946    strong  12.026729  critical   4.689806             low
9   2019  5.114159    strong   9.749355     watch   5.239638        moderate
10  2020 -0.272766      weak  11.878576  critical   5.405162        moderate
11  2021  7.590489    strong  10.886463  critical   6.107936        moderate
12  2022  4.859981  moderate  10.753110  critical   7.659863        moderate
13  2023  5.719992    strong  12.335551  critical   7.671396        moderate
14  2024  4.660196  moderate  13.572976  critical   4.489789             low

In [16]:
summary_df.groupby('gdp_class')[['npl','inflation']].agg({'npl':['mean','count'],'inflation':'mean'}).round(2)

             npl       inflation
            mean count      mean
gdp_class
moderate    8.35     7      6.88
strong      8.57     7      6.94
weak       11.88     1      5.41

In [21]:
summary_df.groupby('npl_class')[['gdp','inflation']].agg({'gdp':['mean','count'],'inflation':'mean'}).round(2),
summary_df.groupby('inflation_class')[['gdp','npl']].agg({'gdp':'mean','npl':'mean'}).round(1)

                 gdp   npl
inflation_class
high             5.1   4.4
low              6.1  10.2
moderate         4.5   8.7

In [23]:
summary_df.groupby(['gdp_class','npl_class'])['inflation'].agg([
    'mean',
    'count',
    'max',
    'min'
]).round(2)

                      mean  count    max    min
gdp_class npl_class
moderate  critical    6.07      2   7.66   4.49
          healthy     9.38      1   9.38   9.38
          watch       6.65      4   8.01   5.72
strong    critical    6.16      3   7.67   4.69
          healthy    14.02      1  14.02  14.02
          watch       5.36      3   6.88   3.96
weak      critical    5.41      1   5.41   5.41